<?php


namespace phpunitExecutionFromPhp;


use PhpExecutionFromPhp\TestExecutor;
use PhpExecutionFromPhp\TestFile;
use PHPUnit\Framework\TestCase;

class CreateDefaultTestFileWithTestFileContentClassTest extends TestCase
{
    protected $temporaryFilesPath;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->temporaryFilesPath = __DIR__ . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . 'temporary_files' . DIRECTORY_SEPARATOR ;
        $this->fixtureFilesPath = __DIR__ . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . 'fixtures' . DIRECTORY_SEPARATOR ;
    }

    public function testExecutionTestIsOk()
    {
        // Arrange
        $defaultTestNameFile = 'DefaultTest';
        $sourceCode = 'public function defaultTestFunction() {}';
        $testFile = new TestFile($this->temporaryFilesPath);
        $testFile->save($defaultTestNameFile, $sourceCode);

        // Check if default test has the correct content
        $testFileContent = $this->getTestFileContent($defaultTestNameFile);
        $defaultTestFileFixtureContent = $this->getDefaultTestFileFixtureContent();
        $isTestFileContentCorrect = ($testFileContent === $defaultTestFileFixtureContent);

        // Assert
        $this->assertTrue($isTestFileContentCorrect, 'Files don\'t have the same content.');
        // Reset the default test file
        $defaultTestFilePath = $this->getTestFilePath($defaultTestNameFile);

        unlink($defaultTestFilePath);
    }

    private function getDefaultTestFileFixtureContent(): string
    {
        $defaultTestFilePath = $this->fixtureFilesPath . 'DefaultTest.php';
        $defaultTestFileContent = file_get_contents($defaultTestFilePath);

        return $defaultTestFileContent;
    }

    /**
     * @param $temporaryFilesPath
     * @param string $defaultTestNameFile
     * @return false|string
     */
    private function getTestFileContent(string $defaultTestNameFile)
    {
        $testFilePath = $this->getTestFilePath($defaultTestNameFile);
        $testFileContent = file_get_contents($testFilePath);

        return $testFileContent;
    }

    /**
     * @param string $defaultTestNameFile
     * @return string
     */
    private function getTestFilePath(string $defaultTestNameFile): string
    {
        $testFilePath = $this->temporaryFilesPath . $defaultTestNameFile . '.php';

        return $testFilePath;
    }

}